name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [21.x]  # Set this to match your local Node version

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Run the server
      run: npm run dev &
      env:
        CI: true
    - name: Run style checker
      run: node format-checker.js
    - name: Run unit tests
      run: npm test
