name: ESLint Check

# Defines when the action will run. 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Jobs represent a sequence of tasks that will be executed as part of the workflow.
jobs:
  run-lint:
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
    - name: Check out source code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'v20.0.0'

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npx eslint . --ext .js --rule 'semi:off'
